### ISSUE TITLE
Incongruences between goldstone landscapes

### ISSUE THREAD

**Issue by 0xangelo** [siemens/industrialbenchmark#8]
Hi all!

I've been experimenting with the IB for a while and noted that the penalty landscape of the mis-calibration subsystem is inconsistent with the images in the original paper. The following is Figure 3 from the paper.
![Screen Shot 2020-03-11 at 11 21 12](https://user-images.githubusercontent.com/12701614/76426927-72bf5580-638a-11ea-87f0-9dbb96234941.png)

I then implemented my own mis-calibration dynamics by following the equations in appendix B: "Goldstone Potential Based Equations". The resulting landscape is as follows.
![MCoriginal](https://user-images.githubusercontent.com/12701614/76432881-54f5ee80-6392-11ea-85c7-8f058ee78253.png)

However, this does not look like the penalty landscapes depicted in the figures before. Looking at the equations, I noticed that this might be due to equation (44):
![Eq44](https://user-images.githubusercontent.com/12701614/76433965-d13d0180-6393-11ea-9c91-86376c6091fe.png)

After a lot of tinkering, I substituted the following equation for the original and achieved similar results to the paper.
![Eq44new](https://user-images.githubusercontent.com/12701614/76434084-f6317480-6393-11ea-8403-402b5da8ffb6.png)
![MCsmooth](https://user-images.githubusercontent.com/12701614/76434111-0184a000-6394-11ea-9e50-71fce65558de.png)

So now I'm not sure which version to use for experiments. Can anyone shine a light on this issue?

**Comment by danielhein84** [comment]
Thank you for reporting this issue. Unfortunately, you are referring to an outdated version of our paper. In the updated version v2 of our paper we removed a typo from eq. 44:
https://arxiv.org/abs/1709.09480

The corrected equation is:
![Bildschirmfoto 2020-05-05 um 10 56 35](https://user-images.githubusercontent.com/1412743/81049845-496d0280-8ebf-11ea-8879-22055ce3a49f.png)
